# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: seeeduino_xiao_ble
    shield: corne_dongle dongle_screen
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: dongle_screen

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_epaper
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_left

  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_epaper
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_right

  - board: nice_nano_v2
    shield: charybdis_left 
    snippet: studio-rpc-usb-uart zmk-usb-logging
    artifact-name: charybdis_left

  - board: nice_nano_v2
    shield: charybdis_right
    snippet: studio-rpc-usb-uart zmk-usb-logging
    artifact-name: charybdis_right

  - board: seeeduino_xiao_ble 
    shield: chipper_left nice_view_adapter nice_epaper
    snippet: studio-rpc-usb-uart zmk-usb-logging
    artifact-name: corne-choc_left

  - board: seeeduino_xiao_ble
    shield: chipper_right nice_view_adapter nice_epaper
    snippet: studio-rpc-usb-uart zmk-usb-logging
    artifact-name: corne-choc_right

  - board: nice_nano_v2
    shield: evo56_left nice_epaper
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: evo56_right nice_epaper

  - board: nice_nano_v2
    shield: evo44_left nice_epaper
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: evo44_right nice_epaper

  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter nice_epaper
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: urchin_left

  - board: nice_nano_v2
    shield: urchin_right nice_view_adapter nice_epaper
    artifact-name: urchin_right

  - board: nice_nano_v2
    shield: petruzia
    artifact-name: petruzia

  - board: nice_nano_v2
    shield: settings_reset
    snippet: studio-rpc-usb-uart zmk-usb-logging
    artifact-name: nice_reset

  - board: seeeduino_xiao_ble 
    shield: settings_reset
    snippet: studio-rpc-usb-uart zmk-usb-logging
    artifact-name: seeed_reset
