manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob

    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: carrefinho
      url-base: https://github.com/carrefinho

    - name: m165437
      url-base: https://github.com/m165437

    - name: badjeff
      url-base: https://github.com/badjeff

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: main

    - name: zmk-adaptive-key
      remote: urob
      path: modules/zmk-adaptive-key
      revision: main
    - name: zmk-auto-layer
      remote: urob
      path: modules/zmk-auto-layer
      revision: main
    - name: zmk-helpers
      remote: urob
      path: modules/zmk-helpers
      revision: main
    - name: zmk-leader-key
      remote: urob
      path: modules/zmk-leader-key
      revision: main
    - name: zmk-tri-state
      remote: urob
      path: modules/zmk-tri-state
      revision: main
    - name: zmk-unicode
      remote: urob
      path: modules/zmk-unicode
      revision: main

    - name: prospector-zmk-module
      remote: carrefinho
      revision: feat/new-status-screens

    - name: nice-view-gem
      remote: m165437
      revision: main

    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main

  self:
    path: config
